### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by jech** [Vivena/babelweb2#2]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x62a1c6]

goroutine 1 [running]:
github.com/Vivena/babelweb2/parser.(*BabelDesc).Update(0x0, 0xc42042c838, 0x2, 0xc420431160, 0x17, 0x6e0cae, 0x5, 0x6e101d, 0x6, 0xc420431720, ...)
        /home/jch/go/src/github.com/Vivena/babelweb2/parser/parser.go:429 +0x136
main.main()
        /home/jch/go/src/github.com/Vivena/babelweb2/main.go:105 +0x573
2017/11/21 13:46:30 Trying [::1]:33123
2017/11/21 13:46:30 dial tcp6 [::1]:33123: getsockopt: connection refused
2017/11/21 13:46:35 dial tcp6 [::1]:33123: getsockopt: connection refused
2017/11/21 13:46:40 Connected to [::1]:33123
2017/11/21 13:46:43 New connection to a websocket
2017/11/21 13:52:34 Connection to [::1]:33123 closed
2017/11/21 13:52:34 Trying [::1]:33123
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x62a1c6]

goroutine 1 [running]:
github.com/Vivena/babelweb2/parser.(*BabelDesc).Update(0x0, 0xc420012688, 0x2, 0xc4200143a0, 0x17, 0x6e0cae, 0x5, 0x6e199a, 0x9, 0xc420012708, ...)
        /home/jch/go/src/github.com/Vivena/babelweb2/parser/parser.go:429 +0x136
main.main()
        /home/jch/go/src/github.com/Vivena/babelweb2/main.go:105 +0x573

**Comment by jech** [comment]
Doesn't your work-around cause a leak?

**Comment by vonaka** [comment]
@jech , normally it doesn't, if there is some leak it's not because of last two commits, I guess.
