### ISSUE TITLE
Zero nodes displayed

### ISSUE THREAD

**Issue by art049** [Vivena/babelweb2#3]
Hello,
I can't display any network informations. Babelweb manage to connect to my babel daemon but everything in the interface seems to be loading forever. I can't choose the current node which is forced to be set to none.
Also on your example [page](http://babelweb.wifi.pps.univ-paris-diderot.fr:8080/), i can see the same behavior.
Thanks

**Comment by vonaka** [comment]
For a couple of days, I don't have access to anything that we can call a router, so it's a bit unfortunate. It looks like with last two or three comments I managed to break something. What you can do, is to switch to 496c8cb04e0d3fcfe14d7d921fd0365e26b68491, if you have the same behaviour at this point, it means that probably it's no our fault. In any case it will be very helpful experiment.

**Comment by art049** [comment]
Thanks, it seems the problem is on my side as using [496c8cb](https://github.com/Vivena/babelweb2/commit/496c8cb04e0d3fcfe14d7d921fd0365e26b68491) doesn't change anything.
Do you have any clue ?
The program seems to be running without any problem.
> 2018/01/04 14:49:30 Trying [::1]:33123
> 2018/01/04 14:49:30 Connected to [::1]:33123

**Comment by vonaka** [comment]
It's hard to say what's your problem, are you sure you managed to communicate with babel daemon? Can you talk to babeld directly? In particular, what's the output of `monitor` command?

**Comment by art049** [comment]
I think i can talk to babeld. 
```
$ echo monitor | netcat -6 ::1 33123
BABEL 0.0
add self pc2 id ba:27:eb:ff:fe:9d:88:53
add neighbour 1032d08 address fe80::ba27:ebff:fe60:9c03 if wlan0 reach ffff rxcost 256 txcost 256 cost 256
add xroute 169.254.64.64/32 prefix 169.254.64.64/32 metric 0
add xroute 192.168.4.1/32 prefix 192.168.4.1/32 metric 0
add xroute 192.168.101.248/32 prefix 192.168.101.248/32 metric 0
add xroute 0.0.0.0/0 prefix 0.0.0.0/0 metric 128
add route 192.168.4.129/32-1032d08 prefix 192.168.4.129/32 installed yes id ba:27:eb:ff:fe:60:9c:03 metric 256 refmetric 0 via fe80::ba27:ebff:fe60:9c03 if wlan0
done
```
babelweb2 should a least show me the node pc2 right ?

**Comment by vonaka** [comment]
Ah, `BABEL 0.0`. Try to update babeld, his "header" has been changed for version 1.0. It's true that perhaps we need to add compatibility with older version, or at least we can print some user-friendly error message.

**Comment by art049** [comment]
Thanks ! That worked.
Yes the error message would be great (On raspbian f.e., 0 0 is the stock repositories version).
Thank you for this great tool !
