### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by jech** [Vivena/babelweb2#5]
Reproducible whenever Babel's socket is closed.

```
panic: interface conversion: interface {} is nil, not string

goroutine 5 [running]:
github.com/Vivena/babelweb2/parser.(*BabelDesc).Fill(0xc4201f2e40, 0xc4200fec00, 0x6e7a26, 0x9)
        /home/jch/go/src/github.com/Vivena/babelweb2/parser/parser.go:542 +0xa3f
main.connection(0xc42005a180, 0x6e8165, 0xb)
        /home/jch/go/src/github.com/Vivena/babelweb2/main.go:50 +0x521
created by main.main
        /home/jch/go/src/github.com/Vivena/babelweb2/main.go:83 +0x1e6
```

**Comment by vonaka** [comment]
@jech, can you, please, confirm that with my last commit I didn't fix anything, but rather completely spoiled it? Thanks.

**Comment by jech** [comment]
Yes, the issue remains.

**Comment by jech** [comment]
https://play.golang.org/p/54FlS0TxhLS

**Comment by vonaka** [comment]
Ahh, long story short, I need to learn golang before writing programs on it.

**Comment by vonaka** [comment]
But, still, what I can't understand is that the panic says that `interface {} is nil ...`, so it's really an interface who is `nil`. If it contains something like `(*T)(nil)` then message must be `interface {} is *T ...` (like in your example if you try to cast `y` to `string`). But I can't imagine situation with this exact panic you got and the false nil test.

Either my proposition that

> before each casting to string we do have verification of "nilness"

is incorrect (and then I really need to question my life choice and maybe abandon programming), or there is something I don't know.

**Comment by jech** [comment]
The bug is easy to reproduce -- just kill the babeld daemon that Babelweb
is speaking to.

**Comment by vonaka** [comment]
Fair enough.

For some (known) reason I can't test anything, but I still believe in the power of my brain saying me that the code from master branch can't produce this *exact* panic. Sorry.

(Yes, I'm kind of playing Ovsienko card, but I don't care.)
