### ISSUE TITLE
404

### ISSUE THREAD

**Issue by dtaht** [Vivena/babelweb2#6]
I just gave this a shot connecting to babeld 1.8.3 (with either the -G or -g options for port 33123)

root@dancer:~/go/bin# ./babelweb2 
2018/10/03 13:02:29 Trying [::1]:33123
2018/10/03 13:02:29 Connected to [::1]:33123

but when trying to access it I get a 404 message from it.

**Comment by MisterDA** [comment]
@dtaht Curiously enough, I was on commit 8ac07b6 and I did had the 404 error.

To BabelWeb2 dev's: it would be a nice cosmetic improvement to have babelweb2 output a line like `Listening on http://[::1]:8080` (with the accurate port). The patch is trivial, but my go-fu is no match for the skills out there.

**Comment by MisterDA** [comment]
@dtaht the issue is that the `babelweb2` binary needs to find the files from the `static/` dir, mostly the css and js, but also a crucial `index.html`. You need to pass the right path to static.
```
  -static string
    	directory with static files (default "./static/")
```

**Comment by dtaht** [comment]
Thank you. I got it running in the right dir now. It eats a lot less cpu than the other version did, but chrome is going wild. An update every second or 4 seconds might be better.

*MY* go-fu is nonexistent.

**Comment by vonaka** [comment]
Luckily for all of us, this is not a go-fu competition.

@dtaht, about the wildness of chrome, I suppose that it can't be more wild than babeld itself, looks like you're a lucky one to catch a really wild babel. We will see what we can do about the delayed update you mentioned.

So, is it ok if I close this one? (For those who don't know, closing issues is my secret passion.)

**Comment by dtaht** [comment]
I am abusing babeld regularly with the https://github.com/dtaht/rtod tool at the moment, trying to make it stand up under 4096 routes or more.
